services:
  - type: web
    name: parking-backend
    env: python
    region: singapore
    plan: free
    rootDir: pleaseBack

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    
    startCommand: |
      python manage.py fix_payments_table &&
      python manage.py fix_booking_db &&
      python manage.py migrate --noinput &&
      python manage.py init_admin &&
      gunicorn backend.wsgi:application


    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"

      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings

      - key: DEBUG
        value: "False"

      - key: SECRET_KEY
        sync: false

      - key: STRIPE_SECRET_KEY
        sync: false

      - key: STRIPE_PUBLIC_KEY
        sync: false

      - key: FRONTEND_URL
        sync: false

      - key: DATABASE_URL
        fromDatabase:
          name: parking-db
          property: connectionString
